name: First GitHub Actions Workflow

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Display tests.txt
        run: cat tests.txt
