name: Run Multiple Jobs Demo

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  palindrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Run Palindrome Program
        run: python palindrome.py

  reverse-words:
    needs: palindrome
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Run Reverse Words Program
        run: python reverse_words.py

  hcf-lcm:
    needs: reverse-words
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Run HCF and LCM Program
        run: python hcf_lcm.py
